<a href="https://colab.research.google.com/github/blancavazquez/CursoDatosMasivosII/blob/master/notebooks/1a_Descomposicion_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descomposición propia de una matriz

Una de los tipos de descomposición matricial más utilizados se llama "descomposición propia" que consiste en descomponer una matriz en un conjuntos de vectores propios y valores propios.

- Los vectores propios (eigenvectores): son vectores unitarios en los cuales su tamaño o magnitud es igual a 1.
- Los valores propios (eigenvalores): son coeficientes aplicados a los valores propios 


#### Importancia de la descomposición de una matriz
- La descomposición puede ser usada para calcular los componentes principales de una matriz en el método de "Análisis de Componentes Principales (PCA, por sus siglas en inglés)" y que se usa para reducir la dimensionalidad de los datos.

Para calcular la descomposición de una matriz A, emplearemos la función de Numpy llamada eig().

In [1]:
from numpy import array
from numpy.linalg import eig

#Se define la matriz
A = array([[9,8,7],[6,5,4],[3,2,1]])
print(A)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [12]:
#Calculando los valores propios y vectores propios
valores, vectores = eig(A)
print("Eigenvalores: \n", valores)
print("Eigenvalores: \n",vectores)

Eigenvalores: 
 [ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
Eigenvalores: 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## Reconstrucción de la matriz original
Es posible reconstruir la matriz original a partir de los vectores propios y valores propios.

In [3]:
from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig

In [11]:
#Se define la matriz
A = array([[1,2,3],[4,5,6],[7,8,9]])
print("Matriz \n", A)
#Calcular los valores y vectores propios
valores, vectores = eig(A)
print("Eigenvalores: \n", valores)
print("Eigenvalores: \n",vectores)

Matriz 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Eigenvalores: 
 [ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
Eigenvalores: 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [5]:
#Crear una matriz a partir de los vectores propios
m_vectores_propios = vectores
print(m_vectores_propios)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [6]:
#Crear una matriz inversa de los vectores propios
m_inversa = inv(m_vectores_propios)
print(m_inversa)

[[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]


In [7]:
#Crear una matriz diagonal para los valores propios
m_diagonal = diag(valores)
print(m_diagonal)

[[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -9.75918483e-16]]


In [8]:
#Reconstruir la matriz original, usando la función producto punto .dot() de numpy
m_original = m_vectores_propios.dot(m_diagonal).dot(m_inversa)
print(m_original)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
