<a href="https://colab.research.google.com/github/blancavazquez/CursoDatosMasivosII/blob/master/notebooks/1a_eigenvalues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descomposición propia de una matriz

Una de los tipos de descomposición matricial más utilizados se llama "descomposición propia" que consiste en descomponer una matriz en un conjuntos de vectores propios y valores propios.

- Los vectores propios (eigenvectores): son vectores unitarios en los cuales su tamaño o magnitud es igual a 1.
- Los valores propios (eigenvalores): son coeficientes aplicados a los valores propios 


#### Importancia de la descomposición de una matriz
- La descomposición puede ser usada para calcular los componentes principales de una matriz en el método de "Análisis de Componentes Principales (PCA, por sus siglas en inglés)" y que se usa para reducir la dimensionalidad de los datos.

Para calcular la descomposición de una matriz A, emplearemos la función de Numpy llamada eig().

In [ ]:
import numpy as np
from numpy import array
from numpy.linalg import eig

#Se define la matriz
A = array([[9,8,7],[6,5,4],[3,2,1]])
print(A)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#Calculando los valores propios y vectores propios usando numpy
valores, vectores = eig(A)
print("Eigenvalores: \n", valores)
print("Eigenvalores: \n",vectores)

Eigenvalores: 
 [ 1.61168440e+01 -1.11684397e+00 -5.03850873e-16]
Eigenvalores: 
 [[-0.8186735  -0.61232756  0.40824829]
 [-0.52532209  0.08675134 -0.81649658]
 [-0.23197069  0.78583024  0.40824829]]


## Reconstrucción de la matriz original
Es posible reconstruir la matriz original a partir de los vectores propios y valores propios.

In [ ]:
from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig

In [ ]:
#Se define la matriz
A = array([[1,2,3],[4,5,6],[7,8,9]])
print("Matriz \n", A)
#Calcular los valores y vectores propios
valores, vectores = eig(A)
print("Eigenvalores: \n", valores)
print("Eigenvalores: \n",vectores)

Matriz 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Eigenvalores: 
 [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvalores: 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
#Crear una matriz a partir de los vectores propios
m_vectores_propios = vectores
print(m_vectores_propios)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
#Crear una matriz inversa de los vectores propios
m_inversa = inv(m_vectores_propios)
print(m_inversa)

[[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]


In [ ]:
#Crear una matriz diagonal para los valores propios
m_diagonal = diag(valores)
print(m_diagonal)

[[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.30367773e-15]]


In [ ]:
#Reconstruir la matriz original, usando la función producto punto .dot() de numpy
m_original = m_vectores_propios.dot(m_diagonal).dot(m_inversa)
print(m_original)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Método de las potencias

El método de las potencias es un método libre de matrices que aproxima los valores y vectores propios de una matriz simétrica. A continuación se explora el cálculo de un par propio (valor y vector propio) usando este método.

El primer código está basado de [Power iteration](http://mlwiki.org/index.php/Power_Iteration) y el segundo de [UCG](https://www.ucg.ac.me/skladiste/blog_10701/objava_23569/fajlovi/power.pdf)

In [ ]:
def eigenvalue(A, v):
    Av = A.dot(v)
    return v.dot(Av)

def power_iteration(A):
    n = A.shape[0] #Tamaño de la matriz (n)

    #Inicializamos el vector
    v = np.ones(n) / np.sqrt(n)
    print("v:", v)
    ev = eigenvalue(A, v)

    while True:
        Av = A.dot(v)
        #se calcula la norma y se normaliza el vector
        v_new = Av / np.linalg.norm(Av)

        ev_new = eigenvalue(A, v_new)
        if np.abs(ev - ev_new) < 0.01:   ##  For complex input, a + ib, the absolute value is sqrt(a**2+b**2)
            print("Umbral:", np.abs(ev - ev_new))
            break

        v = v_new
        ev = ev_new
    return ev_new, v_new

In [ ]:
#Se define la matriz
A = array([[3,2],[2,6]])
power_iteration(A)

v: [0.70710678 0.70710678]
Umbral: 0.0033972229956287237


(6.99969780103031, array([0.45415363, 0.89092339]))

In [ ]:
def power_iteration (A, num_simulations):
  v = np.ones(A.shape[0]) / np.sqrt(A.shape[0]) #se inicializa el vector

  for _ in range(num_simulations):
    # calculate the matrix-by-vector product Ab
    v_new = np.dot(A, v)
    # se calcula la norma  y se re-normaliza el vector
    v = v_new / np.linalg.norm(v_new)
  return v

power_iteration(np.array([[3,2], [2,6]]), 5)

array([0.44778116, 0.89414318])