<a href="https://colab.research.google.com/github/blancavazquez/CursoDatosMasivosII/blob/master/notebooks/3b_pagerank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PageRank en Python
## Formulación básica
En esta libreta programaremos el algoritmo de PageRank y lo aplicaremos a problemas sencillos.

PageRank calcula la relevancia de un conjunto de páginas a partir de la relevancia de los vínculos entrantes. La formulación básica es la siguiente

$$
\mathbf{r}^{(t+1)} = \mathbf{M} \cdot \mathbf{r}^{(t)} 
$$

donde $\mathbf{M}$ es una matriz columna estocástica y $\sum_{i=1}^n r_i = 1$. El cálculo de PageRank es iterativo.

In [1]:
import numpy as np
from scipy.sparse import csr_matrix

def pagerank(M, iter=100):
  n = M.shape[0]
  r = np.ones(n) / n
  for i in range(iter):
    print('Iteración {0}: r = {1}'.format(i,r))
    r = M @ r

  return r

Probemos el algoritmo con el siguiente ejemplo.

![](https://raw.githubusercontent.com/blancavazquez/CursoDatosMasivosII/master/figs/grafo_3nodos.svg)

\begin{align*}
  r_a & = \frac{r_a}{2} + \frac{r_b}{2}\\
  r_b & = \frac{r_a}{2} + r_c\\
  r_c & = \frac{r_b}{2} 
\end{align*}

En su forma matricial
  
\begin{equation*}
\mathbf{M} =
\begin{bmatrix}
\frac{1}{2}           & \frac{1}{2} & 0\\
\frac{1}{2} & 0           & 1\\
0 & \frac{1}{2} & 0
\end{bmatrix}
\end{equation*}


In [2]:
M1 = np.array([[1/2, 1/2, 0], [1/2, 0, 1], [0, 1/2, 0]])
print(M1)

[[0.5 0.5 0. ]
 [0.5 0.  1. ]
 [0.  0.5 0. ]]


Calculamos el PageRank de esta matriz

In [3]:
print(pagerank(M1, 100))

Iteración 0: r = [0.33333333 0.33333333 0.33333333]
Iteración 1: r = [0.33333333 0.5        0.16666667]
Iteración 2: r = [0.41666667 0.33333333 0.25      ]
Iteración 3: r = [0.375      0.45833333 0.16666667]
Iteración 4: r = [0.41666667 0.35416667 0.22916667]
Iteración 5: r = [0.38541667 0.4375     0.17708333]
Iteración 6: r = [0.41145833 0.36979167 0.21875   ]
Iteración 7: r = [0.390625   0.42447917 0.18489583]
Iteración 8: r = [0.40755208 0.38020833 0.21223958]
Iteración 9: r = [0.39388021 0.41601562 0.19010417]
Iteración 10: r = [0.40494792 0.38704427 0.20800781]
Iteración 11: r = [0.39599609 0.41048177 0.19352214]
Iteración 12: r = [0.40323893 0.39152018 0.20524089]
Iteración 13: r = [0.39737956 0.40686035 0.19576009]
Iteración 14: r = [0.40211995 0.39444987 0.20343018]
Iteración 15: r = [0.39828491 0.40449015 0.19722493]
Iteración 16: r = [0.40138753 0.39636739 0.20224508]
Iteración 17: r = [0.39887746 0.40293884 0.1981837 ]
Iteración 18: r = [0.40090815 0.39762243 0.20146942]
Ite

Ahora probemos con el siguiente ejemplo

![](https://raw.githubusercontent.com/blancavazquez/CursoDatosMasivosII/master/figs/grafo_4nodos.svg)

\begin{equation*}
        \mathbf{M} =
        \begin{bmatrix}
        0           & \frac{1}{2} & 1 & 0\\
        \frac{1}{3} & 0           & 0 & \frac{1}{2}\\
        \frac{1}{3} & 0           & 0 & \frac{1}{2}\\
        \frac{1}{3} & \frac{1}{2} & 0 & 0
        \end{bmatrix}
\end{equation*}

In [4]:
M2 = np.array([[0, 1/2, 1, 0], [1/3, 0, 0, 1/2], [1/3, 0, 0, 1/2], [1/3, 1/2, 0, 0]])
print(M2)

[[0.         0.5        1.         0.        ]
 [0.33333333 0.         0.         0.5       ]
 [0.33333333 0.         0.         0.5       ]
 [0.33333333 0.5        0.         0.        ]]


Calculamos su relevancia

In [5]:
print(pagerank(M2, 20))

Iteración 0: r = [0.25 0.25 0.25 0.25]
Iteración 1: r = [0.375      0.20833333 0.20833333 0.20833333]
Iteración 2: r = [0.3125     0.22916667 0.22916667 0.22916667]
Iteración 3: r = [0.34375 0.21875 0.21875 0.21875]
Iteración 4: r = [0.328125   0.22395833 0.22395833 0.22395833]
Iteración 5: r = [0.3359375  0.22135417 0.22135417 0.22135417]
Iteración 6: r = [0.33203125 0.22265625 0.22265625 0.22265625]
Iteración 7: r = [0.33398438 0.22200521 0.22200521 0.22200521]
Iteración 8: r = [0.33300781 0.22233073 0.22233073 0.22233073]
Iteración 9: r = [0.33349609 0.22216797 0.22216797 0.22216797]
Iteración 10: r = [0.33325195 0.22224935 0.22224935 0.22224935]
Iteración 11: r = [0.33337402 0.22220866 0.22220866 0.22220866]
Iteración 12: r = [0.33331299 0.222229   0.222229   0.222229  ]
Iteración 13: r = [0.33334351 0.22221883 0.22221883 0.22221883]
Iteración 14: r = [0.33332825 0.22222392 0.22222392 0.22222392]
Iteración 15: r = [0.33333588 0.22222137 0.22222137 0.22222137]
Iteración 16: r = [0.3

## Trampas de araña
En algunos problemas es posible encontrar trampas de araña, las cuales terminan absorviendo toda la relevancia. Por ej.

![](https://raw.githubusercontent.com/blancavazquez/CursoDatosMasivosII/master/figs/grafo_trampa.svg)


\begin{equation*}
    \mathbf{M}  = \begin{bmatrix}
      0 & \frac{1}{2} & 0\\
      \frac{1}{2} & \frac{1}{2} & 0\\
      \frac{1}{2} & 0 & 1 
      \end{bmatrix}
        \end{equation*}

In [6]:
M3 = np.array([[0, 1/2, 0], [1/2, 1/2, 0], [1/2, 0, 1]])
print(M3)

[[0.  0.5 0. ]
 [0.5 0.5 0. ]
 [0.5 0.  1. ]]


Calculamos su relevancia

In [7]:
pagerank(M3,iter=100)

Iteración 0: r = [0.33333333 0.33333333 0.33333333]
Iteración 1: r = [0.16666667 0.33333333 0.5       ]
Iteración 2: r = [0.16666667 0.25       0.58333333]
Iteración 3: r = [0.125      0.20833333 0.66666667]
Iteración 4: r = [0.10416667 0.16666667 0.72916667]
Iteración 5: r = [0.08333333 0.13541667 0.78125   ]
Iteración 6: r = [0.06770833 0.109375   0.82291667]
Iteración 7: r = [0.0546875  0.08854167 0.85677083]
Iteración 8: r = [0.04427083 0.07161458 0.88411458]
Iteración 9: r = [0.03580729 0.05794271 0.90625   ]
Iteración 10: r = [0.02897135 0.046875   0.92415365]
Iteración 11: r = [0.0234375  0.03792318 0.93863932]
Iteración 12: r = [0.01896159 0.03068034 0.95035807]
Iteración 13: r = [0.01534017 0.02482096 0.95983887]
Iteración 14: r = [0.01241048 0.02008057 0.96750895]
Iteración 15: r = [0.01004028 0.01624552 0.97371419]
Iteración 16: r = [0.00812276 0.0131429  0.97873433]
Iteración 17: r = [0.00657145 0.01063283 0.98279572]
Iteración 18: r = [0.00531642 0.00860214 0.98608144]
Ite

array([1.50711309e-10, 2.43856020e-10, 1.00000000e+00])

## Formulación de Google
La solución a las trampas de araña es la teletransfortación aleatorio. Por lo que podemos reformular el algoritmo de la siguiente manera

\begin{align*}
\mathbf{r}^{(t+1)} & = \mathbf{A} \cdot \mathbf{r}^{(t)}\\
        \mathbf{A} & = \beta \cdot \mathbf{M} + (1 - \beta) \cdot \frac{1}{n} \mathbf{e} \cdot \mathbf{e}^\top
\end{align*}

donde $\mathbf{e}$ es un vector de dimensión $n$ con unos en todos sus elementos

In [8]:
def pagerank_google(M, beta = 0.8, iter=10):
  n = M.shape[0]
  r = np.ones(n) / n
  eeT = np.ones((n, n))
  A = M * beta + (1 - beta) * (eeT / n)
  for i in range(iter):
    print('Iteración {0}: r = {1}'.format(i,r))
    r = A @ r

  return r

Aplicamos esta formulación a nuestro ejemplo anterior

In [9]:
pagerank_google(M3, 0.8, iter=100)

Iteración 0: r = [0.33333333 0.33333333 0.33333333]
Iteración 1: r = [0.2        0.33333333 0.46666667]
Iteración 2: r = [0.2  0.28 0.52]
Iteración 3: r = [0.17866667 0.25866667 0.56266667]
Iteración 4: r = [0.17013333 0.2416     0.58826667]
Iteración 5: r = [0.16330667 0.23136    0.60533333]
Iteración 6: r = [0.15921067 0.22453333 0.616256  ]
Iteración 7: r = [0.15648    0.22016427 0.62335573]
Iteración 8: r = [0.15473237 0.21732437 0.62794325]
Iteración 9: r = [0.15359642 0.21548937 0.63091422]
Iteración 10: r = [0.15286241 0.21430098 0.63283661]
Iteración 11: r = [0.15238706 0.21353202 0.63408092]
Iteración 12: r = [0.15207948 0.2130343  0.63488622]
Iteración 13: r = [0.15188039 0.21271218 0.63540744]
Iteración 14: r = [0.15175154 0.21250369 0.63574477]
Iteración 15: r = [0.15166814 0.21236876 0.6359631 ]
Iteración 16: r = [0.15161417 0.21228143 0.6361044 ]
Iteración 17: r = [0.15157924 0.21222491 0.63619586]
Iteración 18: r = [0.15155663 0.21218832 0.63625505]
Iteración 19: r = [0.

array([0.15151515, 0.21212121, 0.63636364])

## Callejones sin salida
También hay callejones sin salida, los cuales ocurren cuando una página no tiene ningún vínculo saliente. Por ej.

![](https://raw.githubusercontent.com/blancavazquez/CursoDatosMasivosII/master/figs/grafo_callejon.svg)


\begin{equation*}
 \mathbf{M}  = \begin{bmatrix}
      \frac{1}{2} &  \frac{1}{2} & 0\\
      0 & \frac{1}{2} & 0\\
      \frac{1}{2} & 0 & 0 
      \end{bmatrix}
\end{equation*}


In [10]:
M4 = np.array([[1/2, 1/2, 0], [0, 1/2, 0], [1/2, 0, 0]])
print(M4)

[[0.5 0.5 0. ]
 [0.  0.5 0. ]
 [0.5 0.  0. ]]


Su PageRank con la formulación básica

In [11]:
pagerank(M4,iter=100)

Iteración 0: r = [0.33333333 0.33333333 0.33333333]
Iteración 1: r = [0.33333333 0.16666667 0.16666667]
Iteración 2: r = [0.25       0.08333333 0.16666667]
Iteración 3: r = [0.16666667 0.04166667 0.125     ]
Iteración 4: r = [0.10416667 0.02083333 0.08333333]
Iteración 5: r = [0.0625     0.01041667 0.05208333]
Iteración 6: r = [0.03645833 0.00520833 0.03125   ]
Iteración 7: r = [0.02083333 0.00260417 0.01822917]
Iteración 8: r = [0.01171875 0.00130208 0.01041667]
Iteración 9: r = [0.00651042 0.00065104 0.00585938]
Iteración 10: r = [0.00358073 0.00032552 0.00325521]
Iteración 11: r = [0.00195312 0.00016276 0.00179036]
Iteración 12: r = [1.05794271e-03 8.13802083e-05 9.76562500e-04]
Iteración 13: r = [5.69661458e-04 4.06901042e-05 5.28971354e-04]
Iteración 14: r = [3.05175781e-04 2.03450521e-05 2.84830729e-04]
Iteración 15: r = [1.62760417e-04 1.01725260e-05 1.52587891e-04]
Iteración 16: r = [8.64664714e-05 5.08626302e-06 8.13802083e-05]
Iteración 17: r = [4.57763672e-05 2.54313151e-06 

array([2.65583171e-29, 2.62953635e-31, 2.62953635e-29])

Su PageRank con la formulación de Google

In [12]:
pagerank_google(M4, 0.8, iter=100)

Iteración 0: r = [0.33333333 0.33333333 0.33333333]
Iteración 1: r = [0.33333333 0.2        0.2       ]
Iteración 2: r = [0.26222222 0.12888889 0.18222222]
Iteración 3: r = [0.19466667 0.08977778 0.14311111]
Iteración 4: r = [0.14228148 0.06441481 0.10637037]
Iteración 5: r = [0.10354963 0.04663704 0.0777837 ]
Iteración 6: r = [0.07527269 0.03385284 0.05661788]
Iteración 7: r = [0.05469977 0.0245907  0.04115864]
Iteración 8: r = [0.03974613 0.01786622 0.02990985]
Iteración 9: r = [0.02887975 0.0129813  0.02173326]
Iteración 10: r = [0.02098404 0.00943214 0.01579152]
Iteración 11: r = [0.01524699 0.00685337 0.01147413]
Iteración 12: r = [0.01107844 0.00497965 0.00833709]
Iteración 13: r = [0.00804958 0.0036182  0.00605772]
Iteración 14: r = [0.00584881 0.00262898 0.00440153]
Iteración 15: r = [0.00424974 0.00191021 0.00319815]
Iteración 16: r = [0.00308786 0.00138796 0.00232377]
Iteración 17: r = [0.00224363 0.00100849 0.00168845]
Iteración 18: r = [0.00163022 0.00073277 0.00122682]
Ite

array([6.89289117e-15, 3.09828388e-15, 5.18725411e-15])

Los callejones sin salida rompen una de las restricciones de las columnas de $\mathbf{M}$, esto es, que deben sumar 1. Este problema se puede resolver teletransportándose siempre a otra página en los callejones sin salida, lo cual se puede llevar a cabo substituyendo los ceros por $\frac{1}{n}$ en la columna correspondiente 

\begin{equation*}
\mathbf{M}  =  \begin{bmatrix}
      0 & \frac{1}{2} & \frac{1}{3}\\
      \frac{1}{2} & \frac{1}{2} & \frac{1}{3}\\
      \frac{1}{2} & 0 & \frac{1}{3}
      \end{bmatrix}
\end{equation*}

In [13]:
M4_tt = np.array([[1/2, 1/2, 1/3], [0, 1/2, 1/3], [1/2, 0, 1/3]])
print(M4_tt)

[[0.5        0.5        0.33333333]
 [0.         0.5        0.33333333]
 [0.5        0.         0.33333333]]


Si calculamos la relevancia en esta matriz modificada obtenemos lo siguiente

In [14]:
pagerank(M4_tt,iter=20)

Iteración 0: r = [0.33333333 0.33333333 0.33333333]
Iteración 1: r = [0.44444444 0.27777778 0.27777778]
Iteración 2: r = [0.4537037  0.23148148 0.31481481]
Iteración 3: r = [0.44753086 0.22067901 0.33179012]
Iteración 4: r = [0.44470165 0.22093621 0.33436214]
Iteración 5: r = [0.44427298 0.22192215 0.33380487]
Iteración 6: r = [0.44436586 0.22222937 0.33340478]
Iteración 7: r = [0.44443254 0.22224961 0.33331785]
Iteración 8: r = [0.44444702 0.22223076 0.33332222]
Iteración 9: r = [0.4444463  0.22222278 0.33333092]
Iteración 10: r = [0.44444485 0.2222217  0.33333345]
Iteración 11: r = [0.44444442 0.222222   0.33333357]
Iteración 12: r = [0.4444444  0.22222219 0.3333334 ]
Iteración 13: r = [0.44444443 0.22222223 0.33333334]
Iteración 14: r = [0.44444444 0.22222223 0.33333333]
Iteración 15: r = [0.44444445 0.22222222 0.33333333]
Iteración 16: r = [0.44444444 0.22222222 0.33333333]
Iteración 17: r = [0.44444444 0.22222222 0.33333333]
Iteración 18: r = [0.44444444 0.22222222 0.33333333]
Ite

array([0.44444444, 0.22222222, 0.33333333])

In [15]:
pagerank_google(M4_tt, 0.8, iter=100)

Iteración 0: r = [0.33333333 0.33333333 0.33333333]
Iteración 1: r = [0.42222222 0.28888889 0.28888889]
Iteración 2: r = [0.42814815 0.25925926 0.31259259]
Iteración 3: r = [0.42498765 0.2537284  0.32128395]
Iteración 4: r = [0.42382881 0.25383374 0.32233745]
Iteración 5: r = [0.42368834 0.25415682 0.32215484]
Iteración 6: r = [0.42371269 0.25423735 0.32204996]
Iteración 7: r = [0.42372667 0.2542416  0.32203173]
Iteración 8: r = [0.4237291  0.25423843 0.32203246]
Iteración 9: r = [0.423729   0.25423736 0.32203363]
Iteración 10: r = [0.42372885 0.25423725 0.3220339 ]
Iteración 11: r = [0.42372881 0.25423727 0.32203391]
Iteración 12: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 13: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 14: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 15: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 16: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 17: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 18: r = [0.42372881 0.25423729 0.3220339 ]
Ite

array([0.42372881, 0.25423729, 0.3220339 ])

## PageRank escalable
$\mathbf{A}$ es una matriz densa (a diferencia de $\mathbf{M}$), por lo que la memoria requerida crece cuadráticamente respecto a $n$. Una forma más eficiente de calcular PageRank es la siguiente

* Calcula $\hat{\mathbf{r}}^{(t+1)} = \beta \cdot \mathbf{M}\cdot \mathbf{r}^{(t)}$
* Agrega $\frac{\left(1-\beta\right)}{n}$ a los elementos de $\hat{\mathbf{r}}^{(t+1)}$

donde $\beta$ es un hiperparámetro que se fija usualmente en un valor entre 0.8 y 0.9. Aquí presuponemos que no existen callejones sin salida.

In [16]:
def pagerank_escalable_nocss(M, beta = 0.8, iter=100):
  n = M.shape[0]
  r = np.ones(n) / n
  umbn = (1 - beta) / n
  for i in range(iter):
    print('Iteración {0}: r = {1}'.format(i,r))
    rhat = beta * M @ r
    r = rhat + umbn

  return r

In [17]:
pagerank_escalable_nocss(csr_matrix(M3), 0.8, iter=20)

Iteración 0: r = [0.33333333 0.33333333 0.33333333]
Iteración 1: r = [0.2        0.33333333 0.46666667]
Iteración 2: r = [0.2  0.28 0.52]
Iteración 3: r = [0.17866667 0.25866667 0.56266667]
Iteración 4: r = [0.17013333 0.2416     0.58826667]
Iteración 5: r = [0.16330667 0.23136    0.60533333]
Iteración 6: r = [0.15921067 0.22453333 0.616256  ]
Iteración 7: r = [0.15648    0.22016427 0.62335573]
Iteración 8: r = [0.15473237 0.21732437 0.62794325]
Iteración 9: r = [0.15359642 0.21548937 0.63091422]
Iteración 10: r = [0.15286241 0.21430098 0.63283661]
Iteración 11: r = [0.15238706 0.21353202 0.63408092]
Iteración 12: r = [0.15207948 0.2130343  0.63488622]
Iteración 13: r = [0.15188039 0.21271218 0.63540744]
Iteración 14: r = [0.15175154 0.21250369 0.63574477]
Iteración 15: r = [0.15166814 0.21236876 0.6359631 ]
Iteración 16: r = [0.15161417 0.21228143 0.6361044 ]
Iteración 17: r = [0.15157924 0.21222491 0.63619586]
Iteración 18: r = [0.15155663 0.21218832 0.63625505]
Iteración 19: r = [0.

array([0.15153253, 0.21214932, 0.63631815])

In [18]:
pagerank_escalable_nocss(M4_tt, beta=0.8, iter=100)

Iteración 0: r = [0.33333333 0.33333333 0.33333333]
Iteración 1: r = [0.42222222 0.28888889 0.28888889]
Iteración 2: r = [0.42814815 0.25925926 0.31259259]
Iteración 3: r = [0.42498765 0.2537284  0.32128395]
Iteración 4: r = [0.42382881 0.25383374 0.32233745]
Iteración 5: r = [0.42368834 0.25415682 0.32215484]
Iteración 6: r = [0.42371269 0.25423735 0.32204996]
Iteración 7: r = [0.42372667 0.2542416  0.32203173]
Iteración 8: r = [0.4237291  0.25423843 0.32203246]
Iteración 9: r = [0.423729   0.25423736 0.32203363]
Iteración 10: r = [0.42372885 0.25423725 0.3220339 ]
Iteración 11: r = [0.42372881 0.25423727 0.32203391]
Iteración 12: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 13: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 14: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 15: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 16: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 17: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 18: r = [0.42372881 0.25423729 0.3220339 ]
Ite

array([0.42372881, 0.25423729, 0.3220339 ])

Cuando tenemos callejones sin salida, es necesario hacer el siguiente ajuste
* Calcula $\hat{\mathbf{r}}^{(t+1)} = \beta \cdot \mathbf{M}\cdot \mathbf{r}^{(t)}$
* Agrega $\frac{\left(1-\sum_j \hat{r}_j^{(t+1)}\right)}{n}$ a los elementos de $\hat{\mathbf{r}}^{(t+1)}$

In [19]:
def pagerank_escalable_css(M, beta = 0.8, iter=20):
  n = M.shape[0]
  r = np.ones(n) / n
  for i in range(iter):
    print('Iteración {0}: r = {1}'.format(i,r))
    rhat = beta * M @ r
    umrsn = (1 - rhat.sum()) / n
    r = rhat + umrsn

  return r

In [20]:
pagerank_escalable_css(csr_matrix(M3), 0.8, iter=20)

Iteración 0: r = [0.33333333 0.33333333 0.33333333]
Iteración 1: r = [0.2        0.33333333 0.46666667]
Iteración 2: r = [0.2  0.28 0.52]
Iteración 3: r = [0.17866667 0.25866667 0.56266667]
Iteración 4: r = [0.17013333 0.2416     0.58826667]
Iteración 5: r = [0.16330667 0.23136    0.60533333]
Iteración 6: r = [0.15921067 0.22453333 0.616256  ]
Iteración 7: r = [0.15648    0.22016427 0.62335573]
Iteración 8: r = [0.15473237 0.21732437 0.62794325]
Iteración 9: r = [0.15359642 0.21548937 0.63091422]
Iteración 10: r = [0.15286241 0.21430098 0.63283661]
Iteración 11: r = [0.15238706 0.21353202 0.63408092]
Iteración 12: r = [0.15207948 0.2130343  0.63488622]
Iteración 13: r = [0.15188039 0.21271218 0.63540744]
Iteración 14: r = [0.15175154 0.21250369 0.63574477]
Iteración 15: r = [0.15166814 0.21236876 0.6359631 ]
Iteración 16: r = [0.15161417 0.21228143 0.6361044 ]
Iteración 17: r = [0.15157924 0.21222491 0.63619586]
Iteración 18: r = [0.15155663 0.21218832 0.63625505]
Iteración 19: r = [0.

array([0.15153253, 0.21214932, 0.63631815])

In [21]:
pagerank_escalable_css(csr_matrix(M4), 0.8, iter=20)

Iteración 0: r = [0.33333333 0.33333333 0.33333333]
Iteración 1: r = [0.42222222 0.28888889 0.28888889]
Iteración 2: r = [0.42814815 0.25925926 0.31259259]
Iteración 3: r = [0.42498765 0.2537284  0.32128395]
Iteración 4: r = [0.42382881 0.25383374 0.32233745]
Iteración 5: r = [0.42368834 0.25415682 0.32215484]
Iteración 6: r = [0.42371269 0.25423735 0.32204996]
Iteración 7: r = [0.42372667 0.2542416  0.32203173]
Iteración 8: r = [0.4237291  0.25423843 0.32203246]
Iteración 9: r = [0.423729   0.25423736 0.32203363]
Iteración 10: r = [0.42372885 0.25423725 0.3220339 ]
Iteración 11: r = [0.42372881 0.25423727 0.32203391]
Iteración 12: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 13: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 14: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 15: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 16: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 17: r = [0.42372881 0.25423729 0.3220339 ]
Iteración 18: r = [0.42372881 0.25423729 0.3220339 ]
Ite

array([0.42372881, 0.25423729, 0.3220339 ])